name: SimpleHome
main: com.ClexaGod.simplehome.SimpleHome
version: 2.0.0
api: ["2.0.0"]
author: ClexaGod
description: Advanced Home System with UI for PowerNukkitX
permissions:
  simplehome.command.home:
    default: true